api = "0.10"
WithWindowsBuild = false
WithLinuxBuild = false

[buildpack]
  id = "infrabits/cmake"
  version = "0.0.1"

[[targets]]
  os = "linux"
  arch = "amd64"

[[targets]]
  os = "linux"
  arch = "arm64"
